#!/usr/bin/python3.9
from webbrowser import open as openurl
from sys import argv

if len(argv) > 1:
    file = open(argv[1],"r")
else:
    file = open("/home/neriya/.gh_src_urls", "r")
url = file.readline()
while url:
    openurl(url)
    url = file.readline()
file.close()
